FROM node:16-alpine

USER node 

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

COPY  --chown=node:node ./package.json .
RUN npm install
COPY --chown=node:node ./ ./

ENV CHOKIDAR_USEPOLLING true
ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "start"]
